name: farmacia-system

services:
  mariadb:
    image: mariadb:11.2
    container_name: farmacia_db
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: farmacia
      MARIADB_USER: farmacia
      MARIADB_PASSWORD: farmacia123

    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - --connect
        - --innodb_initialized
      interval: 5s
      timeout: 5s
      retries: 20

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: farmacia_broker
    hostname: farmacia-broker
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: farmacia
      RABBITMQ_DEFAULT_PASS: farmacia123

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test:
        - CMD
        - rabbitmq-diagnostics
        - -q
        - ping
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mariadb_data:
  rabbitmq_data: